<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Landlocked</AssemblyName>
    <RootNamespace>Landlocked</RootNamespace>
    <Description>Progressive, process-wide Landlock restrictions for .NET on Linux.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IsTrimmable>true</IsTrimmable>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Landlocked.LowLevel/Landlocked.LowLevel.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Landlocked.Tests" />
    <None Include="../../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
